In [1]:
import numpy as np

In [2]:
a = np.array((1,2,3))

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array((2,3,4))

In [5]:
b

array([2, 3, 4])

In [6]:
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])